import { Lato } from "next/font/google";
import "./globals.css";

const inter = Lato({ 
  subsets: ["latin"],
  weight: ['100','300','400','700','900'],
 });

export const metadata = {
  title: "Nextjs Assignment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
